---
title: "p"
output:
  pdf_document: default
  html_document: default
date: "2023-05-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load-packages, message = FALSE}
library(tidyverse)
library(dplyr)
library(tidymodels)
library(schrute)
library(lubridate)
```


```{r }
TEDS <-read.csv("C:/Users/User/Desktop/proj/proj_data.csv")
```
```{r}
TEDS
```
```{r}
TEDS <- filter(TEDS,DSMCRIT %in% c(14,15,16,17))
value_to_drop <- -9  #drop all rows that have missing values
keeps <- c("STFIPS","EDUC","AGE","DIVISION","SERVICES","NOPRIOR","PSOURCE","EMPLOY","METHUSE","PSYPROB","GENDER","DSMCRIT","RACE","SUB1","FREQ1","FREQ_ATND_SELF_HELP","VET","LIVARAG","ARRESTS")
TEDS <- TEDS[keeps]
TEDS <- TEDS[rowSums(TEDS == value_to_drop, na.rm = TRUE) == 0, ]
TEDS

```

```{r }
# fix all values
# TEDS$AGE[TEDS$AGE == 1] <- '12-14'
# TEDS$AGE[TEDS$AGE == 2] <- '15-17'
# TEDS$AGE[TEDS$AGE == 3] <- '18-20'
# TEDS$AGE[TEDS$AGE == 4] <- '21-24'
# TEDS$AGE[TEDS$AGE == 5] <- '25-29'
# TEDS$AGE[TEDS$AGE == 6] <- '30-34'
# TEDS$AGE[TEDS$AGE == 7] <- '35-39'
# TEDS$AGE[TEDS$AGE == 8] <- '40-44'
# TEDS$AGE[TEDS$AGE == 9] <- '45-49'
# TEDS$AGE[TEDS$AGE == 10]<- '50-54'
# TEDS$AGE[TEDS$AGE == 11]<- '55-60'
# TEDS$AGE[TEDS$AGE == 12]<- '65+'

TEDS$DIVISION[TEDS$DIVISION == 0]<- 'US jurisdiction/territory'
TEDS$DIVISION[TEDS$DIVISION == 1]<- 'New England'
TEDS$DIVISION[TEDS$DIVISION == 2]<- 'Middle Atlantic'
TEDS$DIVISION[TEDS$DIVISION == 3]<- 'East North Central'
TEDS$DIVISION[TEDS$DIVISION == 4]<- 'West North Central'
TEDS$DIVISION[TEDS$DIVISION == 5]<- 'South Atlantic'
TEDS$DIVISION[TEDS$DIVISION == 6]<- 'East South Central'
TEDS$DIVISION[TEDS$DIVISION == 7]<- 'West South Central'
TEDS$DIVISION[TEDS$DIVISION == 8]<- 'Mountain'
TEDS$DIVISION[TEDS$DIVISION == 9]<- 'Pacific'

# TEDS$LIVARAG[TEDS$LIVARAG == 1]<- 'Homeless'
# TEDS$LIVARAG[TEDS$LIVARAG == 2]<- 'Dependent living'
# TEDS$LIVARAG[TEDS$LIVARAG == 3]<- 'Independent living'


# TEDS$EDUC[TEDS$EDUC == 1] <- 'under grade 9'
# TEDS$EDUC[TEDS$EDUC == 2] <- 'Grades 9 to 11'
# TEDS$EDUC[TEDS$EDUC == 3] <- 'Grade 12'
# TEDS$EDUC[TEDS$EDUC == 4] <- '1-3 years of high education'
# TEDS$EDUC[TEDS$EDUC == 5] <- '4 years of high education'

TEDS$RACE[TEDS$RACE == 1] <- 'Alaska Native'
TEDS$RACE[TEDS$RACE == 2] <- 'American Indian'
TEDS$RACE[TEDS$RACE == 3] <- 'Asian or Pacific Islander'
TEDS$RACE[TEDS$RACE == 4] <- 'Black or African American'
TEDS$RACE[TEDS$RACE == 5] <- 'White'
TEDS$RACE[TEDS$RACE == 6] <- 'Asian'
TEDS$RACE[TEDS$RACE == 7] <- 'Other single race'
TEDS$RACE[TEDS$RACE == 8] <- 'Two or more races'
TEDS$RACE[TEDS$RACE == 9] <- 'Native Hawaiian or Other Pacific Islander'

TEDS$EMPLOY[TEDS$EMPLOY == 1] <- 3
TEDS$EMPLOY[TEDS$EMPLOY == 2] <- 2
TEDS$EMPLOY[TEDS$EMPLOY == 3] <- 1
TEDS$EMPLOY[TEDS$EMPLOY == 4] <- 0

TEDS$STFIPS[TEDS$STFIPS == 1] <- 'Alabama'
TEDS$STFIPS[TEDS$STFIPS == 2] <- 'Alaska'
TEDS$STFIPS[TEDS$STFIPS == 4] <- 'Arizona'
TEDS$STFIPS[TEDS$STFIPS == 5] <- 'Arkansas'
TEDS$STFIPS[TEDS$STFIPS == 6] <- 'California'
TEDS$STFIPS[TEDS$STFIPS == 8] <- 'Colorado'
TEDS$STFIPS[TEDS$STFIPS == 9] <- 'Connecticut'
TEDS$STFIPS[TEDS$STFIPS == 10] <- 'Delaware'
TEDS$STFIPS[TEDS$STFIPS == 11] <- 'District of Columbia'
TEDS$STFIPS[TEDS$STFIPS == 12] <- 'Florida'
TEDS$STFIPS[TEDS$STFIPS == 13] <- 'Georgia'
TEDS$STFIPS[TEDS$STFIPS == 15] <- 'Hawaii'
TEDS$STFIPS[TEDS$STFIPS == 17] <- 'Illinois'
TEDS$STFIPS[TEDS$STFIPS == 18] <- 'Indiana'
TEDS$STFIPS[TEDS$STFIPS == 19] <- 'Iowa'
TEDS$STFIPS[TEDS$STFIPS == 20] <- 'Kansas'
TEDS$STFIPS[TEDS$STFIPS == 21] <- 'Kentucky'
TEDS$STFIPS[TEDS$STFIPS == 22] <- 'Louisiana'
TEDS$STFIPS[TEDS$STFIPS == 23] <- 'Maine'
TEDS$STFIPS[TEDS$STFIPS == 25] <- 'Massachusetts'
TEDS$STFIPS[TEDS$STFIPS == 26] <- 'Michigan'
TEDS$STFIPS[TEDS$STFIPS == 27] <- 'Minnesota'
TEDS$STFIPS[TEDS$STFIPS == 28] <- 'Mississippi'
TEDS$STFIPS[TEDS$STFIPS == 29] <- 'Missouri'
TEDS$STFIPS[TEDS$STFIPS == 30] <- 'Montana'
TEDS$STFIPS[TEDS$STFIPS == 31] <- 'Nebraska'
TEDS$STFIPS[TEDS$STFIPS == 32] <- 'Nevada'
TEDS$STFIPS[TEDS$STFIPS == 33] <- 'New Hampshire'
TEDS$STFIPS[TEDS$STFIPS == 34] <- 'New Jersey'
TEDS$STFIPS[TEDS$STFIPS == 36] <- 'New York'
TEDS$STFIPS[TEDS$STFIPS == 37] <- 'North Carolina'
TEDS$STFIPS[TEDS$STFIPS == 38] <- 'North Dakota'
TEDS$STFIPS[TEDS$STFIPS == 39] <- 'Ohio'
TEDS$STFIPS[TEDS$STFIPS == 40] <- 'Oklahoma'
TEDS$STFIPS[TEDS$STFIPS == 42] <- 'Pennsylvania'
TEDS$STFIPS[TEDS$STFIPS == 44] <- 'Rhode Island'
TEDS$STFIPS[TEDS$STFIPS == 45] <- 'South Carolina'
TEDS$STFIPS[TEDS$STFIPS == 46] <- 'South Dakota'
TEDS$STFIPS[TEDS$STFIPS == 47] <- 'Tennessee'
TEDS$STFIPS[TEDS$STFIPS == 48] <- 'Texas'
TEDS$STFIPS[TEDS$STFIPS == 49] <- 'Utah'
TEDS$STFIPS[TEDS$STFIPS == 50] <- 'Vermont'
TEDS$STFIPS[TEDS$STFIPS == 51] <- 'Virginia'
TEDS$STFIPS[TEDS$STFIPS == 54] <- 'West Virginia'
TEDS$STFIPS[TEDS$STFIPS == 55] <- 'Wisconsin'
TEDS$STFIPS[TEDS$STFIPS == 56] <- 'Wyoming'
TEDS$STFIPS[TEDS$STFIPS == 72] <- 'Puerto Rico'

TEDS$SERVICES[TEDS$SERVICES == 1] <- 'Detox, 24-hour, hospital inpatient'
TEDS$SERVICES[TEDS$SERVICES == 2] <- 'Detox, 24-hour, free-standing residential'
TEDS$SERVICES[TEDS$SERVICES == 3] <- 'Rehab/residential, hospital (non-detox)'
TEDS$SERVICES[TEDS$SERVICES == 4] <- 'Rehab/residential, short term '
TEDS$SERVICES[TEDS$SERVICES == 5] <- 'Rehab/residential, long term '
TEDS$SERVICES[TEDS$SERVICES == 6] <- 'Ambulatory, iop'
TEDS$SERVICES[TEDS$SERVICES == 7] <- 'Ambulatory, non-iop'
TEDS$SERVICES[TEDS$SERVICES == 8] <- 'Ambulatory, detoxification'
TEDS$SERVICES[TEDS$SERVICES == -9] <- 'missing'

# TEDS$NOPRIOR[TEDS$NOPRIOR == 0] 
# TEDS$NOPRIOR[TEDS$NOPRIOR == 1] <- 'One prior treatment episode'
# TEDS$NOPRIOR[TEDS$NOPRIOR == 2] <- 'Two prior treatment episodes'
# TEDS$NOPRIOR[TEDS$NOPRIOR == 3] <- 'Three prior treatment episodes'
# TEDS$NOPRIOR[TEDS$NOPRIOR == 4] <- 'Four prior treatment episodes'
# TEDS$NOPRIOR[TEDS$NOPRIOR == 5] <- 'Five or more prior treatment episodes'
# TEDS$NOPRIOR[TEDS$NOPRIOR == -9] <- 'Missing'

TEDS$PSOURCE[TEDS$PSOURCE == 1] <- 'Individual (includes self-referral)'
TEDS$PSOURCE[TEDS$PSOURCE == 2] <- 'Alcohol/drug use care provider'
TEDS$PSOURCE[TEDS$PSOURCE == 3] <- 'Other health care provider'
TEDS$PSOURCE[TEDS$PSOURCE == 4] <- 'School (educational)'
TEDS$PSOURCE[TEDS$PSOURCE == 5] <- 'Employer/EAP'
TEDS$PSOURCE[TEDS$PSOURCE == 6] <- 'Other community referral'
TEDS$PSOURCE[TEDS$PSOURCE == 7] <- 'Court/criminal justice referral/DUI/DWI'
TEDS$PSOURCE[TEDS$PSOURCE == -9] <- 'Missing'

TEDS$PSYPROB[TEDS$PSYPROB == 1] <- 1
TEDS$PSYPROB[TEDS$PSYPROB == 2] <- 0


TEDS$GENDER[TEDS$GENDER == -9] <- 'Missing'
TEDS$GENDER[TEDS$GENDER == 1] <- 'Male'
TEDS$GENDER[TEDS$GENDER ==2]<-'Female'

TEDS$METHUSE[TEDS$METHUSE == 1] <- 1
TEDS$METHUSE[TEDS$METHUSE == 2] <- 0


TEDS$FREQ1[TEDS$FREQ1 == 1] <- 0
TEDS$FREQ1[TEDS$FREQ1 == 2] <- 1
TEDS$FREQ1[TEDS$FREQ1 == 3] <- 2
TEDS$FREQ1[TEDS$FREQ1 == -9] <- 'Missing'

TEDS$DSMCRIT[TEDS$DSMCRIT == 1] <- 'Alcohol-induced disorder'
TEDS$DSMCRIT[TEDS$DSMCRIT == 2] <- 'Substance-induced disorder'
TEDS$DSMCRIT[TEDS$DSMCRIT == 2] <- 'Substance-induced disorder'
TEDS$DSMCRIT[TEDS$DSMCRIT == 3] <- 'Alcohol intoxication'
TEDS$DSMCRIT[TEDS$DSMCRIT == 4] <- 'Alcohol dependence'
TEDS$DSMCRIT[TEDS$DSMCRIT == 5] <- 'Opioid dependence'
TEDS$DSMCRIT[TEDS$DSMCRIT == 6] <- 'Cocaine dependence'
TEDS$DSMCRIT[TEDS$DSMCRIT == 7] <- 'Cannabis dependence'
TEDS$DSMCRIT[TEDS$DSMCRIT == 8] <- 'Other substance dependence'
TEDS$DSMCRIT[TEDS$DSMCRIT == 9] <- 'Alcohol abuse'
TEDS$DSMCRIT[TEDS$DSMCRIT == 10] <- 'Cannabis abuse'
TEDS$DSMCRIT[TEDS$DSMCRIT == 11] <- 'Other substance abuse'
TEDS$DSMCRIT[TEDS$DSMCRIT == 12] <- 'Opioid abuse'
TEDS$DSMCRIT[TEDS$DSMCRIT == 13] <- 'Cocaine abuse'
TEDS$DSMCRIT[TEDS$DSMCRIT == 14] <- 'Anxiety disorders'
TEDS$DSMCRIT[TEDS$DSMCRIT == 15] <- 'Depressive disorders'
TEDS$DSMCRIT[TEDS$DSMCRIT == 16] <- 'Schizophrenia/other psychotic disorders'
TEDS$DSMCRIT[TEDS$DSMCRIT == 17] <- 'Bipolar disorders'
TEDS$DSMCRIT[TEDS$DSMCRIT == 18] <- 'Attention deficit/disruptive behavior disorders'
TEDS$DSMCRIT[TEDS$DSMCRIT == 19] <- 'Other mental health condition '
TEDS$DSMCRIT[TEDS$DSMCRIT == -9] <-'missing'

TEDS$FREQ_ATND_SELF_HELP[TEDS$FREQ_ATND_SELF_HELP == 1] <-0
TEDS$FREQ_ATND_SELF_HELP[TEDS$FREQ_ATND_SELF_HELP == 2] <-1
TEDS$FREQ_ATND_SELF_HELP[TEDS$FREQ_ATND_SELF_HELP == 3] <-2
TEDS$FREQ_ATND_SELF_HELP[TEDS$FREQ_ATND_SELF_HELP == 4] <-3
TEDS$FREQ_ATND_SELF_HELP[TEDS$FREQ_ATND_SELF_HELP == 5] <-1
TEDS$FREQ_ATND_SELF_HELP[TEDS$FREQ_ATND_SELF_HELP == -9] <-'Missing'
TEDS <- TEDS[TEDS$FREQ_ATND_SELF_HELP != 5, ]

TEDS$SUB1[TEDS$SUB1 == -9] <- 'Missing'
TEDS$SUB1[TEDS$SUB1 == 1] <- 'None'
TEDS$SUB1[TEDS$SUB1 == 2] <- 'Alcohol'
TEDS$SUB1[TEDS$SUB1 == 3] <- 'Cocaine/crack'
TEDS$SUB1[TEDS$SUB1 == 4] <- 'Marijuana/hashish'
TEDS$SUB1[TEDS$SUB1 == 5] <- 'Heroin'
TEDS$SUB1[TEDS$SUB1 == 6] <- 'Non-prescription methadone'
TEDS$SUB1[TEDS$SUB1 == 7] <- 'Other opiates and synthetics'
TEDS$SUB1[TEDS$SUB1 == 8] <- 'PCP'
TEDS$SUB1[TEDS$SUB1 == 9] <- 'Hallucinogens'
TEDS$SUB1[TEDS$SUB1 == 10] <- 'Methamphetamine/speed'
TEDS$SUB1[TEDS$SUB1 == 11] <- 'Other amphetamines'
TEDS$SUB1[TEDS$SUB1 == 12] <- 'Other stimulants'
TEDS$SUB1[TEDS$SUB1 == 13] <- 'Benzodiazepines'
TEDS$SUB1[TEDS$SUB1 == 14] <- 'Other tranquilizers'
TEDS$SUB1[TEDS$SUB1 == 15] <- 'Barbiturates'
TEDS$SUB1[TEDS$SUB1 == 16] <- 'Other sedatives or hypnotics'
TEDS$SUB1[TEDS$SUB1 == 17] <- 'Inhalants'
TEDS$SUB1[TEDS$SUB1 == 18] <- 'Over-the-counter medications'
TEDS$SUB1[TEDS$SUB1 == 19] <- 'Other drugs'

TEDS$VET[TEDS$VET == 2] <- 0

```
```{r}
g1 <- ggplot(data = TEDS, aes(x = DSMCRIT,fill= DSMCRIT)) +
  geom_bar() +
  ylab("disorder")+ theme(axis.text.x = element_text(angle = 45, hjust = 1))

g1
filterd<-TEDS %>%
  group_by(SUB1) %>%
  filter(n() > 30)
filterd <- within(filterd, SUB1 <- factor(SUB1, levels=names(sort(table(SUB1), decreasing=TRUE))))
g2 <- ggplot(data = filterd, aes(x = SUB1,fill= SUB1)) +
  geom_bar() +
  ylab("count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

g2+ facet_grid(DSMCRIT ~ .)

filterd<-TEDS %>%
  group_by(SERVICES) %>%
  filter(n() > 30)
filterd <- within(filterd, SERVICES <- factor(SERVICES, levels=names(sort(table(SERVICES), decreasing=TRUE))))
g3 <- ggplot(data = filterd, aes(x = SERVICES,fill= SERVICES)) +
  geom_bar() +
  ylab("count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

g3+ facet_grid(DSMCRIT ~ .)

```
`
```{r}
library(vcd)
library(rcompanion)

data <- TEDS

col_names <- colnames(data)
cor_matrix <- matrix(NA, nrow = length(col_names), ncol = length(col_names), dimnames = list(col_names, col_names))
for (i in 1:length(col_names)) {
  for (j in 1:length(col_names)) {
    cor_matrix[i, j] <- cramerV(data[, i], data[, j])
  }
}

cor_df <- melt(cor_matrix)  # Reshape into a long format

ggplot(cor_df, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "red") +
  labs(title = "Cramer's V Correlation Heatmap") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
library(vcd)
Anxiety_data<-TEDS
Depressive_data<-TEDS
Schizophrenia_data<-TEDS
Bipolar_data<-TEDS
Anxiety_data$Anxiety<- ifelse(Anxiety_data$DSMCRIT == "Anxiety disorders",1,0)
Depressive_data$Depressive<- ifelse(Depressive_data$DSMCRIT == "Depressive disorders",1,0)
Schizophrenia_data$Schizophrenia<- ifelse(Schizophrenia_data$DSMCRIT == "Schizophrenia/other psychotic disorders",1,0)
Bipolar_data$Bipolar<- ifelse(Bipolar_data$DSMCRIT == "Bipolar disorders",1,0)

```
```{r}
library(rcompanion)
library(vcd)
library(reshape2)
cramer_result <- vector("numeric", length = ncol(Anxiety_data) - 1)
for (i in 2:ncol(Anxiety_data)) {
  cramer_result[i-1] <- cramerV(Anxiety_data$Anxiety, Anxiety_data[,i])
}
column_names <- names(Anxiety_data)[-1]
a <- data.frame(Column = column_names, Anxiety = cramer_result)

for (i in 2:ncol(Depressive_data)) {
  cramer_result[i-1] <- cramerV(Depressive_data$Depressive, Depressive_data[,i])
}
column_names <- names(Depressive_data)[-1]
b <- data.frame(Column = column_names, Depressive = cramer_result)

for (i in 2:ncol(Schizophrenia_data)) {
  cramer_result[i-1] <- cramerV(Schizophrenia_data$Schizophrenia, Schizophrenia_data[,i])
}
column_names <- names(Schizophrenia_data)[-1]
c <- data.frame(Column = column_names, Schizophrenia = cramer_result)

for (i in 2:ncol(Bipolar_data)) {
  cramer_result[i-1] <- cramerV(Bipolar_data$Bipolar, Bipolar_data[,i])
}
column_names <- names(Bipolar_data)[-1]
d <- data.frame(Column = column_names, Bipolar = cramer_result)
df1= merge(a,b,by="Column")
df2 = merge(c,d,by="Column")
merged= merge(df1,df2,by="Column")

merged_long <- melt(merged, id.vars = "Column")
heatmap_plot <- ggplot(merged_long, aes(x = variable, y =Column , fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "red") +
  labs(x = "Disorder", y = "Variable", fill = "Cramer") +
  ggtitle("Correlation for each disorder")
heatmap_plot + theme(axis.text.x = element_text(angle = 90, hjust = 1))
heatmap_plot

```

```{r}
library(caret)
set.seed(123)
Anxiety_data <- Anxiety_data %>% 
  mutate_if(is.numeric, as.factor)
split <- initial_split(Anxiety_data, prop = 0.80)
train_data <- training(split)
test_data <- testing(split)

Anxiety_data$Anxiety <- factor(Anxiety_data$Anxiety)
# Create a recipe
Anxiety_rec <- recipe(Anxiety ~ ., data = train_data) %>%
step_rm(DSMCRIT,DIVISION,FREQ1,VET,ARRESTS) %>%
  step_dummy(all_nominal(),-all_outcomes())

# Fit a logistic regression model
Anxiety_mod <- logistic_reg() %>%
  set_engine("glm")

Anxiety_wflow <- workflow() %>%
  add_model(Anxiety_mod) %>%
  add_recipe(Anxiety_rec)

Anxiety_fit <- Anxiety_wflow %>%
  fit(data = train_data)

tidy(Anxiety_fit) %>% print()

pred <- predict(Anxiety_fit, test_data, type = "prob") %>% 
  bind_cols(test_data)
cutoff_prob <- 0.18


tp = nrow(pred[pred$.pred_1>cutoff_prob & pred$Anxiety == 1, ])
fp = nrow(pred[pred$.pred_1>cutoff_prob & pred$Anxiety == 0, ])
tn = nrow(pred[pred$.pred_0>cutoff_prob & pred$Anxiety == 0, ])
fn = nrow(pred[pred$.pred_1<cutoff_prob & pred$Anxiety == 1, ])
cat("tp:",tp,"\n")
cat("fp:",fp,"\n")
cat("tn:",tn,"\n")
cat("fn:",fn,"\n")
precision <- tp / (tp + fp)
recall <- tp / (tp + fn)
f1_score <- 2 * precision * recall / (precision + recall)
cat("percision:",precision,"\n")
cat("recall:",recall,"\n")
cat("f1_score:",f1_score,"\n")

library(pROC)
actuals=pred$Anxiety
probs=pred$.pred_1
roc_auc <- auc(roc(actuals, probs))
roc_auc
library(pROC)  # For calculating AUC-ROC
library(ggplot2)  # For plotting the graph
#data <- data.frame(predicted_probabilities, actual_labels)
roc_obj <- roc(pred$Anxiety, pred$.pred_1)

plot_obj <- ggroc(roc_obj)
plot(plot_obj)

```

```{r}
library(caret)
set.seed(123)
Depressive_data <- Depressive_data %>% 
  mutate_if(is.numeric, as.factor)
split <- initial_split(Depressive_data, prop = 0.80)
train_data <- training(split)
test_data <- testing(split)


Depressive_data$Depressive <- factor(Depressive_data$Depressive)
# Create a recipe
Depressive_rec <- recipe(Depressive ~ ., data = train_data) %>%
step_rm(DSMCRIT,DIVISION,FREQ1,VET,ARRESTS,	GENDER,	METHUSE) %>%
  step_dummy(all_nominal(),-all_outcomes())

# Fit a logistic regression model
Depressive_mod <- logistic_reg() %>%
  set_engine("glm")

Depressive_wflow <- workflow() %>%
  add_model(Depressive_mod) %>%
  add_recipe(Depressive_rec)

Depressive_fit <- Depressive_wflow %>%
  fit(data = train_data)

tidy(Depressive_fit) %>% print()

pred <- predict(Depressive_fit, test_data, type = "prob") %>% 
  bind_cols(test_data)
cutoff_prob <- 0.18



tp = nrow(pred[pred$.pred_1>cutoff_prob & pred$Depressive == 1, ])
fp = nrow(pred[pred$.pred_1>cutoff_prob & pred$Depressive == 0, ])
tn = nrow(pred[pred$.pred_0>cutoff_prob & pred$Depressive == 0, ])
fn = nrow(pred[pred$.pred_1<cutoff_prob & pred$Depressive == 1, ])
cat("tp:",tp,"\n")
cat("fp:",fp,"\n")
cat("tn:",tn,"\n")
cat("fn:",fn,"\n")
precision <- tp / (tp + fp)
recall <- tp / (tp + fn)
f1_score <- 2 * precision * recall / (precision + recall)
cat("percision:",precision,"\n")
cat("recall:",recall,"\n")
cat("f1_score:",f1_score,"\n")

library(pROC)
actuals=pred$Depressive
probs=pred$.pred_1
roc_auc <- auc(roc(actuals, probs))
roc_auc
library(pROC)  # For calculating AUC-ROC
library(ggplot2)  # For plotting the graph
#data <- data.frame(predicted_probabilities, actual_labels)
roc_obj <- roc(pred$Depressive, pred$.pred_1)

plot_obj <- ggroc(roc_obj)
plot(plot_obj)

```

```{r}
library(caret)
set.seed(123)
Schizophrenia_data <- Schizophrenia_data %>% 
  mutate_if(is.numeric, as.factor)
split <- initial_split(Schizophrenia_data, prop = 0.80)
train_data <- training(split)
test_data <- testing(split)

Schizophrenia_data$Schizophrenia <- factor(Schizophrenia_data$Schizophrenia)
# Create a recipe
Schizophrenia_rec <- recipe(Schizophrenia ~ ., data = train_data) %>%
step_rm(DSMCRIT,ARRESTS,	DIVISION,PSYPROB) %>%
  step_dummy(all_nominal(),-all_outcomes())

# Fit a logistic regression model
Schizophrenia_mod <- logistic_reg() %>%
  set_engine("glm")

Schizophrenia_wflow <- workflow() %>%
  add_model(Schizophrenia_mod) %>%
  add_recipe(Schizophrenia_rec)

Schizophrenia_fit <- Schizophrenia_wflow %>%
  fit(data = train_data)

tidy(Schizophrenia_fit) %>% print()

pred <- predict(Schizophrenia_fit, test_data, type = "prob") %>% 
  bind_cols(test_data)
cutoff_prob <- 0.2



tp = nrow(pred[pred$.pred_1>cutoff_prob & pred$Schizophrenia == 1, ])
fp = nrow(pred[pred$.pred_1>cutoff_prob & pred$Schizophrenia == 0, ])
tn = nrow(pred[pred$.pred_0>cutoff_prob & pred$Schizophrenia == 0, ])
fn = nrow(pred[pred$.pred_1<cutoff_prob & pred$Schizophrenia == 1, ])
cat("tp:",tp,"\n")
cat("fp:",fp,"\n")
cat("tn:",tn,"\n")
cat("fn:",fn,"\n")
precision <- tp / (tp + fp)
recall <- tp / (tp + fn)
f1_score <- 2 * precision * recall / (precision + recall)
cat("percision:",precision,"\n")
cat("recall:",recall,"\n")
cat("f1_score:",f1_score,"\n")

library(pROC)
actuals=pred$Schizophrenia
probs=pred$.pred_1
roc_auc <- auc(roc(actuals, probs))
roc_auc
library(pROC)  # For calculating AUC-ROC
library(ggplot2)  # For plotting the graph
#data <- data.frame(predicted_probabilities, actual_labels)
roc_obj <- roc(pred$Schizophrenia, pred$.pred_1)

plot_obj <- ggroc(roc_obj)
plot(plot_obj)

```

```{r}
library(caret)
set.seed(123)
Bipolar_data <- Bipolar_data %>% 
  mutate_if(is.numeric, as.factor)
split <- initial_split(Bipolar_data, prop = 0.80)
train_data <- training(split)
test_data <- testing(split)


Bipolar_data$Bipolar <- factor(Bipolar_data$Bipolar)
# Create a recipe
Bipolar_rec <- recipe(Bipolar ~ ., data = train_data) %>%
step_rm(DSMCRIT,DIVISION,LIVARAG,METHUSE) %>%
  step_dummy(all_nominal(),-all_outcomes())

# Fit a logistic regression model
Bipolar_mod <- logistic_reg() %>%
  set_engine("glm")

Bipolar_wflow <- workflow() %>%
  add_model(Bipolar_mod) %>%
  add_recipe(Bipolar_rec)

Bipolar_fit <- Bipolar_wflow %>%
  fit(data = train_data)

tidy(Bipolar_fit) %>% print()

pred <- predict(Bipolar_fit, test_data, type = "prob") %>% 
  bind_cols(test_data)
cutoff_prob <- 0.15



tp = nrow(pred[pred$.pred_1>cutoff_prob & pred$Bipolar == 1, ])
fp = nrow(pred[pred$.pred_1>cutoff_prob & pred$Bipolar == 0, ])
tn = nrow(pred[pred$.pred_0>cutoff_prob & pred$Bipolar == 0, ])
fn = nrow(pred[pred$.pred_1<cutoff_prob & pred$Bipolar == 1, ])
cat("tp:",tp,"\n")
cat("fp:",fp,"\n")
cat("tn:",tn,"\n")
cat("fn:",fn,"\n")
precision <- tp / (tp + fp)
recall <- tp / (tp + fn)
f1_score <- 2 * precision * recall / (precision + recall)
cat("percision:",precision,"\n")
cat("recall:",recall,"\n")
cat("f1_score:",f1_score,"\n")

library(pROC)
actuals=pred$Bipolar
probs=pred$.pred_1
roc_auc <- auc(roc(actuals, probs))
roc_auc
library(pROC)  # For calculating AUC-ROC
library(ggplot2)  # For plotting the graph
#data <- data.frame(predicted_probabilities, actual_labels)
roc_obj <- roc(pred$Bipolar, pred$.pred_1)

plot_obj <- ggroc(roc_obj)
plot(plot_obj)

```
